### PR TITLE
fixes, closes #121 #122 #126 #127

### LINKED ISSUE #121: species: Retrieval of species release
iCount species -r 84
Executing the following command: iCount species -r 84
Input parameters for function 'species' in iCount.genomes.ensembl
    release: 84
[TypeError] unorderable types: int() <= str()
  File "/Users/mozosi/Programs/ENV/env_iCount/lib/python3.5/site-packages/iCount-2.0.0.dev0-py3.5.egg/iCount/cli.py", line 438, in main
    result_object = func(**args)

  File "/Users/mozosi/Programs/ENV/env_iCount/lib/python3.5/site-packages/iCount-2.0.0.dev0-py3.5.egg/iCount/genomes/ensembl.py", line 101, in species
    if not MIN_RELEASE_SUPPORTED <= release <= MAX_RELEASE_SUPPORTED:

### PR DESCRIPTION
**Pull request by JureZmrzlikar**

### CODE REVIEW

**Comment by tomazc** [comment]
@JureZmrzlikar please sign the CLA.

**Comment by tomazc** [comment]
@JureZmrzlikar, please check and fix the linters issue in travis.

**Comment by JureZmrzlikar** [comment]
@tomazc : commit 3c66679 does indeed fix the repeated columns issue. The problem was that input variable with filename was overridden with the contents of the file. While logging the inputs, whole content of the file was logged. At that stage file is not merged yet, so output appeared as it was result, but with duplicated lines.

**Comment by JureZmrzlikar** [comment]
@tomazc : all tests pass, except coverage. Do you insist on making a positive diff, or is it OK? I removed some tests, since they were failing for some strange mocking reasons... I personally don't think it is worth bothering, but my opinion may be biased :-)

**Comment by tomazc** [comment]
@JureZmrzlikar, great, thanks!

**Pull request merged**
