### PR TITLE
genomes: Add GENCODE as source of genome and annotation

### PR DESCRIPTION
**Pull request by JureZmrzlikar**

### CODE REVIEW

**Comment by tomazc** [comment]
@JureZmrzlikar, update the CLI reference file, which is part of the documentation, by running:
```
cd docs
iCount man > source/ref_CLI.txt
```
and then add the `source/ref_CLI.txt` into the commit for this PR.

**Comment by JureZmrzlikar** [comment]
Isn't this meant to be done (only) during prepartion of release?

**Comment by tomazc** [comment]
The documentation is (re)generated at each commit to the master branch...

**Comment by tomazc** [comment]
@JureZmrzlikar, great job! Thanks for including gencode.

**Pull request merged**
